//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DESTRA_PROD> DESTRA_PROD { get; set; }
        public DbSet<EXPTES_PROD> EXPTES_PROD { get; set; }
        public DbSet<LIB_A_RUB_PROD> LIB_A_RUB_PROD { get; set; }
        public DbSet<SUBDESTIN_PROD> SUBDESTIN_PROD { get; set; }
        public DbSet<TABGEN_PROD> TABGEN_PROD { get; set; }
        public DbSet<TRAMIT_PROD> TRAMIT_PROD { get; set; }
        public DbSet<TRANSFORMACION> TRANSFORMACION { get; set; }
        public DbSet<VISTAREC> VISTAREC { get; set; }
    }
}
