//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMIT_PROD
    {
        public int TRANROCORR { get; set; }
        public string TRACODHABI { get; set; }
        public string TRACODTRAM { get; set; }
        public DateTime? TRAFECHACT { get; set; }
        public Nullable<System.DateTime> TRAFECHAFT { get; set; }
        public string TRAREGTRAM { get; set; }
        public Nullable<int> TRAREFTRAM { get; set; }
        public Nullable<int> TRANROTRAM { get; set; }
        public Nullable<short> TRAGRPTRAM { get; set; }
        public Nullable<short> TRAFOJAS { get; set; }
        public string TRACONEXPE { get; set; }
        public Nullable<System.DateTime> TRAFECREG { get; set; }
        public Nullable<System.DateTime> TRAFECREGNA { get; set; }
        public string TRADESISTE { get; set; }
        public string TRAREQCONTABLE { get; set; }
        public string TRADIGITAL { get; set; }
    }
}
