//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFORMACION
    {
        public int TRFNROCORR_ANT { get; set; }
        public int TRFNROCORR_ACT { get; set; }
        public string TRFCODTRAM { get; set; }
        public Nullable<int> TRFNROTRAM { get; set; }
        public System.DateTime TRFFECHACT { get; set; }
        public string TRFUSUACTU { get; set; }
        public System.DateTime TRFFECACTU { get; set; }
        public Nullable<short> TRFTIPOSOC_ANT { get; set; }
        public Nullable<short> TRFTIPOSOC_ACT { get; set; }
    }
}
