//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTAREC
    {
        public int VISNROCORR { get; set; }
        public string VISCODTRAM { get; set; }
        public System.DateTime VISFECHACT { get; set; }
        public Nullable<int> VISNROTRAM { get; set; }
        public string VISCODDEST { get; set; }
        public Nullable<System.DateTime> VISFECHART { get; set; }
        public Nullable<short> VISNROSUBD { get; set; }
        public string VISTIPO { get; set; }
        public string VISDETALLE { get; set; }
        public Nullable<System.DateTime> VISFECACTU { get; set; }
        public string VISUSUACTU { get; set; }
        public Nullable<System.DateTime> VISFECBAJA { get; set; }
        public string VISCODBAJA { get; set; }
        public Nullable<short> VISREVISOR { get; set; }
        public Nullable<short> VISREVOK { get; set; }
        public Nullable<short> VISNHOJA { get; set; }
        public string VISFIN { get; set; }
        public Nullable<short> VISPZONOTIF { get; set; }
        public string VISDIGITAL { get; set; }
        public string VISDATREG { get; set; }
        public Nullable<int> VISIDBPM { get; set; }
    }
}
