//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLSACOM
    {
        public int BOLNROCORR { get; set; }
        public string BOLCODTRAM { get; set; }
        public System.DateTime BOLFECHACT { get; set; }
        public Nullable<int> BOLNROTRAM { get; set; }
        public Nullable<System.DateTime> BOLFECFVIG { get; set; }
        public string BOLUSUACTU { get; set; }
        public Nullable<System.DateTime> BOLFECACTU { get; set; }
        public Nullable<System.DateTime> BOLFECVIGE { get; set; }
        public string BOLNRORESOL { get; set; }
        public Nullable<int> BOLNROFVIG { get; set; }
        public Nullable<System.DateTime> BOLFECDESDE { get; set; }
    }
}
