//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPTES
    {
        public int EXPNROCORR { get; set; }
        public string EXPCODHABI { get; set; }
        public Nullable<int> EXPEXPREFE { get; set; }
        public Nullable<System.DateTime> EXPFECHACC { get; set; }
        public short EXPTIPOSOC { get; set; }
        public string EXPRAZONSO { get; set; }
        public string EXPADITAME { get; set; }
        public string EXPSALIO { get; set; }
        public Nullable<short> EXPFOJAS { get; set; }
        public Nullable<long> EXPNROCUIT { get; set; }
        public Nullable<System.DateTime> EXPFECVTO { get; set; }
        public string EXPREGULAR { get; set; }
        public string EXPAHORRO { get; set; }
        public string EXPCODBAJA { get; set; }
        public Nullable<System.DateTime> EXPFECBAJA { get; set; }
        public string EXPART118 { get; set; }
        public string EXPART123 { get; set; }
        public string EXPTIPOCON { get; set; }
        public string EXPDIGITAL { get; set; }
        public string EXPBALANCES { get; set; }
        public string EXPDDJJ { get; set; }
        public string EXPRAZONSOINS { get; set; }
        public Nullable<int> EXPNRORESERVA { get; set; }
        public string EXPUSUARIOSAE { get; set; }
        public Nullable<decimal> EXPHOMONIMIAID { get; set; }
    }
}
