//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GORDON : DbContext
    {
        public GORDON()
            : base("name=GORDON")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLSACOM> BOLSACOM { get; set; }
        public DbSet<DESTRA> DESTRA { get; set; }
        public DbSet<EXPTES> EXPTES { get; set; }
        public DbSet<SUBDESTIN> SUBDESTIN { get; set; }
        public DbSet<TABGEN> TABGEN { get; set; }
        public DbSet<TRAMITE_DESISTIDO> TRAMITE_DESISTIDO { get; set; }
        public DbSet<VISTAREC> VISTAREC { get; set; }
        public DbSet<VISTAS> VISTAS { get; set; }
    }
}
