//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBDESTIN
    {
        public string SUBDESTINO { get; set; }
        public short SUBNROSUBD { get; set; }
        public string SUBNOMBRE { get; set; }
        public string SUBPASSW { get; set; }
        public string SUBVISTA { get; set; }
        public Nullable<System.DateTime> SUBFECBAJ { get; set; }
        public string SUBUSUARIO { get; set; }
    }
}
