//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABGEN
    {
        public string TABTIPOTAB { get; set; }
        public string TABCLAVE { get; set; }
        public string TABCONTEN1 { get; set; }
        public string TABCONTEN2 { get; set; }
        public string TABCONTEN3 { get; set; }
        public string TABCONTEN4 { get; set; }
        public string TABCONTEN5 { get; set; }
    }
}
