//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAMITE_DESISTIDO
    {
        public int TRDNROCORR { get; set; }
        public int TRDNROTRAM_ORIG { get; set; }
        public System.DateTime TRDFECHACT_ORIG { get; set; }
        public string TRDCODTRAM_ORIG { get; set; }
        public int TRDNROTRAM_DES { get; set; }
        public System.DateTime TRDFECHACT_DES { get; set; }
        public string TRDCODTRAM_DES { get; set; }
        public short TRDNCAJA { get; set; }
        public int TRDNROPE { get; set; }
        public string TRDUSUACTU { get; set; }
        public System.DateTime TRDFECACTU { get; set; }
    }
}
