//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.GORDONARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTAS
    {
        public decimal VISVISTAID { get; set; }
        public int VISNROCORR { get; set; }
        public int VISNROTRAM { get; set; }
        public string VISCODTRAM { get; set; }
        public System.DateTime VISFECHACT { get; set; }
        public short VISNROVERSION { get; set; }
        public decimal VISTIPOVISTAID { get; set; }
        public string VISTEXT { get; set; }
        public string VISINSPECTORID { get; set; }
        public System.DateTime VISFECACTU { get; set; }
        public string VISREVISORID { get; set; }
        public Nullable<System.DateTime> VISFECREVISION { get; set; }
        public string VISTEXTREVISOR { get; set; }
        public decimal VISESTADOID { get; set; }
        public string VISTIPOPROFINTERVINIENTE { get; set; }
        public string VISACEPTREVISOR { get; set; }
        public string VISAYUDAMEMORIA { get; set; }
    }
}
