//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_GDE
    {
        public int GDENROCORR { get; set; }
        public string GDECODTRAM { get; set; }
        public System.DateTime GDEFECHACT { get; set; }
        public int GDENROTRAM { get; set; }
        public string GDECODACT { get; set; }
        public string GDECODANT { get; set; }
        public string GDEUSUACTU { get; set; }
        public System.DateTime GDEFECACTU { get; set; }
    }
}
