//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTRA
    {
        public int DTRNROCORR { get; set; }
        public string DTRCODTRAM { get; set; }
        public System.DateTime DTRFECHACT { get; set; }
        public Nullable<int> DTRNROTRAM { get; set; }
        public string DTRCODDEST { get; set; }
        public string DTRUSUDEST { get; set; }
        public System.DateTime DTRFECHART { get; set; }
        public string DTRDESTANT { get; set; }
        public Nullable<System.DateTime> DTRFECHAST { get; set; }
        public Nullable<short> DTRNROSUBD { get; set; }
    }
}
