//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_DOMICILIOS
    {
        public int MDONROCORR { get; set; }
        public int MDONROTRAM { get; set; }
        public string MDOTIPODOM { get; set; }
        public string MDOCALLE { get; set; }
        public string MDONUMERO { get; set; }
        public string MDOPISO { get; set; }
        public string MDODPTO { get; set; }
        public string MDOCODPOS { get; set; }
        public string MDOLOCAL { get; set; }
        public string MDOUSUACTU { get; set; }
        public System.DateTime MDOFECACTU { get; set; }
    }
}
