//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_INSCRIPCION
    {
        public int MAINROCORR { get; set; }
        public int MAINROTRAM { get; set; }
        public string MAINROINS { get; set; }
        public string MAILIBRO { get; set; }
        public int MAIFOLIO { get; set; }
        public System.DateTime MAIFECINS { get; set; }
        public string MAIUSUACTU { get; set; }
        public System.DateTime MAIFECACTU { get; set; }
    }
}
