//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_SEGUROCAU
    {
        public int MSGNROCORR { get; set; }
        public int MSGNROTRAM { get; set; }
        public string MSGCODCIA { get; set; }
        public string MSGNPOLIZA { get; set; }
        public Nullable<System.DateTime> MSGFDESDE { get; set; }
        public Nullable<System.DateTime> MSGHASTA { get; set; }
        public Nullable<decimal> MSGIMPORTE { get; set; }
        public string MSGUSUACTU { get; set; }
        public System.DateTime MSGFECACTU { get; set; }
        public string MSGTIPO { get; set; }
    }
}
