//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULADOS
    {
        public int MATNROCORR { get; set; }
        public string MATCODTRAM { get; set; }
        public int MATNROTRAM { get; set; }
        public System.DateTime MATFECHACT { get; set; }
        public string MATNOMBRE { get; set; }
        public string MATTIPOMAT { get; set; }
        public string MATRAMO { get; set; }
        public string MATTIPODOC { get; set; }
        public string MATNRODOC { get; set; }
        public string MATNACION { get; set; }
        public string MATESTCIV { get; set; }
        public Nullable<System.DateTime> MATFECNAC { get; set; }
        public Nullable<long> MATCUIT { get; set; }
        public string MATUSUACTU { get; set; }
        public System.DateTime MATFECACTU { get; set; }
        public string MATMATREFE { get; set; }
    }
}
