//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARGA : DbContext
    {
        public ARGA()
            : base("name=ARGA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DATOS_GDE> DATOS_GDE { get; set; }
        public DbSet<DESTRA> DESTRA { get; set; }
        public DbSet<EXPTES> EXPTES { get; set; }
        public DbSet<MAT_CERTVIGENCIA> MAT_CERTVIGENCIA { get; set; }
        public DbSet<MAT_DOMICILIOS> MAT_DOMICILIOS { get; set; }
        public DbSet<MAT_INSCRIPCION> MAT_INSCRIPCION { get; set; }
        public DbSet<MAT_SEGUROCAU> MAT_SEGUROCAU { get; set; }
        public DbSet<MATRICULADOS> MATRICULADOS { get; set; }
        public DbSet<TABGEN> TABGEN { get; set; }
        public DbSet<TIMBRADOS> TIMBRADOS { get; set; }
        public DbSet<TRAMIT> TRAMIT { get; set; }
        public DbSet<VISTAREC> VISTAREC { get; set; }
    }
}
