//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgaAPI.Data.ARGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMBRADOS
    {
        public short TIMNCAJA { get; set; }
        public int TIMNROPE { get; set; }
        public long TIMNROFOR { get; set; }
        public System.DateTime TIMFECTIM { get; set; }
        public string TIMCONTROL { get; set; }
        public decimal TIMMONTO { get; set; }
        public Nullable<int> TIMNROCORR { get; set; }
        public string TIMCODTRAM { get; set; }
        public Nullable<System.DateTime> TIMFECHACT { get; set; }
        public Nullable<int> TIMNROTRAM { get; set; }
        public Nullable<System.DateTime> TIMFECBAJA { get; set; }
        public Nullable<short> TIMOPERADOR { get; set; }
        public string TIMCODRET { get; set; }
        public Nullable<System.DateTime> TIMFECACTU { get; set; }
        public Nullable<int> TIMTRAMENTE { get; set; }
        public Nullable<int> TIMCORRENTE { get; set; }
        public Nullable<int> TIMNROORIG { get; set; }
        public string TIMCODWEB { get; set; }
        public string TIMTIPOFOR { get; set; }
        public string TIMCODREIN { get; set; }
        public Nullable<int> TIMNROTRAMREIN { get; set; }
        public Nullable<System.DateTime> TIMFECHACTREIN { get; set; }
        public Nullable<decimal> TIMMONTOREIN { get; set; }
    }
}
